### ISSUE TITLE
input and output

### ISSUE THREAD

**Issue by zji90** [AltschulerWu-Lab/scScope#10]
Hi,
I wonder whether the input should be raw count matrix or normalized count matrix (e.g. normalized by library size or log transformed)? Also has the output already adjusted for library size and log transformed?
Thanks!

**Comment by zji90** [comment]
I have tried scscope on an 10x dataset with around 2000 cells. The dataset is prefiltered so that only genes with positive expressions in at least 10% cells are retained. The prefilitered data is then scran normalized to account for library size and then log2 transformed after adding pseudocount of 1. scscope is then run with default parameters. 
I find that in the output of scscope, nearly 25% of all genes have zero expressions across all cells. Plus the clustering performance is really bad for a dataset with three distinct cell types. The three cell types are all mixed together. I think I must be running the program in a wrong way. Is it because I am passing in the prenormalized and log transformed data instead of the raw counts?
Thanks!

**Comment by fbao-fudan** [comment]
> Hi,
> I wonder whether the input should be raw count matrix or normalized count matrix (e.g. normalized by library size or log transformed)? Also has the output already adjusted for library size and log transformed?
> Thanks!

We prefer to have a normalized input. We didnot require a specific normalization method. In our implementation, we didnot consider the library size adjustment.

**Comment by fbao-fudan** [comment]
> I have tried scscope on an 10x dataset with around 2000 cells. The dataset is prefiltered so that only genes with positive expressions in at least 10% cells are retained. The prefilitered data is then scran normalized to account for library size and then log2 transformed after adding pseudocount of 1. scscope is then run with default parameters.
> I find that in the output of scscope, nearly 25% of all genes have zero expressions across all cells. Plus the clustering performance is really bad for a dataset with three distinct cell types. The three cell types are all mixed together. I think I must be running the program in a wrong way. Is it because I am passing in the prenormalized and log transformed data instead of the raw counts?
> Thanks!

There is no problem in your data preprocessing. Can you check the loss curve to make sure the method coverges after taining? And how many genes left after filtering?
