### ISSUE TITLE
Can't install with pip install scScope

### ISSUE THREAD

**Issue by AllenWu18** [AltschulerWu-Lab/scScope#11]
When I run pip install scScope on my PC, it showed like below:
Collecting scScope
  Using cached https://files.pythonhosted.org/packages/25/a2/e655113922130e26a2fba0b8ce007ba5955843ed1c34a75cbd40e88b9b6f/scScope-0.1.5-py2.py3-none-any.whl
Collecting phenograph (from scScope)
  Could not find a version that satisfies the requirement phenograph (from scScope) (from versions: )
No matching distribution found for phenograph (from scScope)

So how to deal with it? I think my computer has satisfied other requirements.
Thx ! :)

**Comment by fbao-fudan** [comment]
Hi Allen,

Thank you for your interest in our work. Please follow the instruction herehttps://github.com/jacoblevine/PhenoGraph to install phonograph.

Best,
Feng

**Comment by fbao-fudan** [comment]
There was an isssue from PhenoGraph when working with scipy. And this was fixed with latest version.
