### ISSUE TITLE
Reconstruction error code

### ISSUE THREAD

**Issue by biosyssun** [AltschulerWu-Lab/scScope#12]
Thanks for your beautiful work. I found some inconsistencies related to the 'Reconstruction error' between the definition in you paper and the implementation in the 202 line of the __init__.py file. What happened? Thank you very much.

**Comment by fbao-fudan** [comment]
> Thanks for your beautiful work. I found some inconsistencies related to the 'Reconstruction error' between the definition in you paper and the implementation in the 202 line of the **init**.py file. What happened? Thank you very much.

Thank you for your interest. Can you provide more details on what the inconsistancy is?

**Comment by fbaothu** [comment]
Did not receive further reply
