### ISSUE TITLE
embryonic mouse brains

### ISSUE THREAD

**Issue by akdess** [AltschulerWu-Lab/scScope#2]
Thanks a lot for this great study.  I would appreciate if you can provide the cell type /cluster  annotation output of scScope for embryonic mouse brain data. 

Thanks a lot!

**Comment by fbao-fudan** [comment]
Yes. Please leave an email.
Thank you!

**Comment by akdess** [comment]
I would appreciate if you can write your email adress. I sent an email to Yue.Deng@ucsf.edu but probably it escaped your notice. Thanks a lot!

**Comment by zacharylau10** [comment]
hi, could you send me the annotation file? e-mail: lj-p@live.cn.
Thanks a lot!
