### ISSUE TITLE
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

### ISSUE THREAD

**Issue by xuebaliang** [AltschulerWu-Lab/scScope#8]
I recently run your code on some other dataset. But when I take out the latent representation, I find it has many nan value.  Do you meet it? What's your solution?

**Comment by fbao-fudan** [comment]
> I recently run your code on some other dataset. But when I take out the latent representation, I find it has many nan value. Do you meet it? What's your solution?

I did not meet this circumstance. You can try to perform data filtering before inputing them to scScope, eg removing genes with lots of zero entris, normalizing data using library size. You can follow our data preprocessing steps in demo.py.
