### ISSUE TITLE
how to determine encoder and decoder structure

### ISSUE THREAD

**Issue by zji90** [AltschulerWu-Lab/scScope#9]
Hi,
I wonder how I can choose 'encoder_layers' and 'decoder_layers' parameters? Is there any default parameters or they can be chosen using some cross-validation process? Also if I leave them as encoder_layers=[], decoder_layers=[], does that mean the autoencoder is not run at all?
Thanks!

**Comment by fbao-fudan** [comment]
> Hi,
> I wonder how I can choose 'encoder_layers' and 'decoder_layers' parameters? Is there any default parameters or they can be chosen using some cross-validation process? Also if I leave them as encoder_layers=[], decoder_layers=[], does that mean the autoencoder is not run at all?
> Thanks!


Thank you for your interest. Parameters are randomly initialized and are optimized through training by minimizing the reconstruction error of non-zero entries.  encoder_layers=[], decoder_layers=[] mean there is no **additional** layer to the default network structure described in the paper.

**Comment by zji90** [comment]
Thanks for your response!
